### PR TITLE
fix(api): exit early when API key is invalid (#53)

### LINKED ISSUE #53: Exit early when API key is invalid
Currently, when an invalid API key is provided, the test generator keeps retrying until all attempts are exhausted.

Example logs:

```dart
[2026-01-16 15:23:05.853800] [TestGenerator] [INFO] Generating tests for Trace.parseVM_40753_1_test.dart (attempt 3 of 5)
[2026-01-16 15:23:12.948043] [TestGenerator] [WARNING] Error encountered: api key not valid. please pass a valid api key.
[2026-01-16 15:23:12.948142] [TestGenerator] [INFO] Generating tests for Trace.parseVM_40753_1_test.dart (attempt 4 of 5) 
[2026-01-16 15:23:13.322346] [TestGenerator] [WARNING] Error encountered: api key not valid. please pass a valid api key. 
[2026-01-16 15:23:13.322443] [TestGenerator] [INFO] Generating tests for Trace.parseVM_40753_1_test.dart (attempt 5 of 5) 
[2026-01-16 15:23:13.981707] [TestGenerator] [WARNING] Error encountered: api key not valid. please pass a valid api key.
```

Instead, execution should exit immediately once an invalid API key is detected, since retries won’t succeed without a valid key.

### PR DESCRIPTION
**Pull request by jaideepkathiresan**
- Fixes #53 
## Summary of changes

- **Early Exit on Invalid API Key:**  
  Updated `TestGenerator` to immediately stop execution and throw a `StateError` when an `"api key not valid"` error is returned from the LLM, preventing unnecessary retries

- **Test Coverage:**  
  Added a unit test in `test_generator_test.dart` to verify that the generator exits correctly when an invalid API key is encountered

### CODE REVIEW

**Comment by jaideepkathiresan** [comment]
Hi @AmrAhmed119, this is my first time contributing to this repo. Could you take a look at this PR and share your feedback. Thanks!

File: lib/src/LLM/test_generator.dart [hunk 1]
```diff
@@ -190,6 +190,14 @@ class TestGenerator {
           continue;
         }
 
+        if (errorMessage.contains('api key not valid')) {
+          status = TestStatus.failed;
+          await testFile.deleteTest();
```
Comment (AmrAhmed119) [inline lib/src/LLM/test_generator.dart]: If the api key is invalid, no tests would have been generated, so there’s no need to call `deleteTest()` or update `status` here.

Also instead of throwing a new `StateError`, we could simply use `rethrow` to preserve and benefit from the existing exception types provided by the `google_generative_ai` package.

**Review by AmrAhmed119 — COMMENTED** [review]
Just a small simplification suggestion, Thanks

**Comment by jaideepkathiresan** [comment]
@AmrAhmed119, understood. Will be pushing a commit incorporating these changes. Thank-you!

**Comment by jaideepkathiresan** [comment]
@AmrAhmed119, I've made the changes. Could you check the latest commit?

**Comment by liamappelbe** [comment]
@jaideepkathiresan Looks like you need a `dart format`. Remember to always `dart format` and `dart analyze` your code before you push it. It saves time to do this yourself because the github bots have to be manually approved to run by us, and won't actually run the tests if there are formatting/analysis errors.

**Comment by jaideepkathiresan** [comment]
@liamappelbe thanks for the reminder. I'll make sure to run `dart format` and `dart analyze` locally before pushing future commits. I will also push a commit fixing the CI error.

**Comment by jaideepkathiresan** [comment]
Hi @liamappelbe, I have run `dart format` and `dart analyze` locally and found no errors.
I hope the CI errors would be fixed now.

**Review by AmrAhmed119 — APPROVED** [review]

**Comment by AmrAhmed119** [comment]
Thanks for your Contribution! @jaideepkathiresan
